hero:
  title_en: 都市を森に。
  title_ja: |-
    <div style="text-align: left;"><br>『木造建築2.0』<br>――ノスタルジーではない、構造科学だ。

    <br>建築OSが導く「縮退時代のスマート減災」</div>　　
profile:
  bio: '<div style="text-align: left;">未来研究家。<br> AI、経済、働き方の奥にある
    「時代を動かす力学」を読み解く。<br> 未来予測だけでなく、 未来を理解するために。<br>経歴：竹中技術研究所、プリンストン大学。</div>'
  career: '<div style="text-align: left;">2027年：AI設計の一般化
    ハイブリッド構造（S造×木造）の設計自動化AIが普及。<br>地方工務店でも、コストと構造を瞬時に最適化した「非住宅木造」を提案。<br>
    2028年：スクラップ＆ビルドではなく、既存の鉄骨ビルの価値を「木」で高めるリノベーション。<br>都市の古い雑居ビルが、次々と木質オフィスへと生まれ変わる。
    <br>2030年：空と木の融合 木造ドローンポートが主要駅の屋上に常設。<br>空のモビリティと、温もりのある木造インフラが日常の風景。</div>'
  substack_url: https://phitouc.substack.com/
